create table if not exists public.feedback_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 2 and 120),
  contact text not null check (char_length(trim(contact)) between 3 and 160),
  message text not null check (char_length(trim(message)) between 5 and 4000),
  created_at timestamptz not null default now()
);

alter table public.feedback_messages enable row level security;

drop policy if exists "Anyone can insert feedback" on public.feedback_messages;
create policy "Anyone can insert feedback"
on public.feedback_messages for insert
with check (true);

drop policy if exists "No public read feedback" on public.feedback_messages;
create policy "No public read feedback"
on public.feedback_messages for select
using (false);
